### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by meleu** [meleu/hascheevos#17]
- [ ] update the `cheevoshash.c` (references: [RADocs](https://docs.retroachievements.org/Game-Identification/) and [`cheevos.c`](https://github.com/libretro/RetroArch/blob/deb5c9b03ccfc12ac9e6a47be23728ef042a6e16/cheevos/cheevos.c#L2966))
  - [ ] new nes hashing
  - [ ] new snes hashing
  - [ ] add lynx hashing

- [ ] simplify the process of checking if a game ID has cheevos by using the [`officialgameslist` request](https://github.com/RetroAchievements/RAWeb/commit/5abfb953f889e396f4b6e8c50dce784d78a1c1a3#diff-033feb7461dd3db6c058d97dcb25a06b).

---

get hashlibrary
get officicialgameslist
hash rom
get game id (from hashlibrary)
get console shortname (from hashlibrary filename)
check officialgameslist if game id is present

---

## Hash entire file:

- Famicom - fds - |.fds|.nes
- N64 - n64 - |.z64|.n64|.v64
- GB - gb - |.gb
- GBC - gbc - |.gbc
- GBA - gba - |.gba
- VirtualBoy - virtualboy - |.vb
- Pokemon Mini - pokemini - |.min
- Master System - mastersystem - |.bin|.sms
- Mega Drive - megadrive|genesis - |.bin|.gen|md|.sg|.smd
- Sega 32X - sega32x - |.32x|.bin|.md|.smd
- Game Gear - gamegear - |.bin|.gg|.sms
- Atari 2600 - atari2600 - |.a26|.bin|.rom
- Atari 7800 - atari7800 - |.a78|.bin
- Atari Jaguar - atarijaguar - |.j64|.jag
- ColecoVision - coleco - |.col|.rom
- NeoGeo Pocket - ngp - |.ngp
- NeoGeo Pocket Color - ngpc - |.ngc
- PCEngine - pcengine - |.ccd|.chd|.cue|.pce
- WonderSwan - wonderswan - |.ws
- WonderSwan Color - wonderswancolor - |.wsc

## Different hashing methods:

- NES - nes - |.fds|.nes
- SNES - snes - |.fig|.mgd|.sfc|.smc|.swc
- Sega CD - segacd - |.bin|.chd|.cue|.iso
- Atari Lynx - atarilynx - |.lnx
- PCEngine CD - pcengine - |.ccd|.chd|.cue|.pce
- Arcade - fba|arcade - nome do arquivo sem extensão
- PlayStation - psx - |.cue|.ccd|.chd|.exe|.iso|.m3u|.pbp|.toc
- Nintendo DS - nds - |.nds
- Sega CD - segacd - |.bin|.chd|.cue|.iso

## Undocummented

- SG-1000 - sg-1000 - |.bin|.sg

## Unsupported by libretro/RetroArch

- PC-8001/8801
- Apple II 

---

## melhorias para o hascheevos

108: `check_dependencies()`
- declarar `DEPS` como global e colocar no início do script
- não oferecer `apt-get` (distro-agnostic)
- case insensitve bash regex tests 

364: `game_has_cheevos()`: adaptar essa função para o json que será retornado por `r=officialgameslist`.

307: `get_game_id()`: essa função vai ter que mudar quando começarmos a usar md5sum puro (ver abaixo).

440: `get_rom_hash()`: usar md5sum puro (não depender do cheevoshash.c).

**Comment by chewvodka** [comment]
:) Nice!  I like seeing updates!  Will this be available through the `--update` command or do I need to redownload and recompile?

**Comment by meleu** [comment]
take it easy dude!

this is just my To Do list! :sweat_smile:

**Comment by chewvodka** [comment]
I realized that after I commented lol.  Quick question though.. Could you add another checkbox to add support for "hack" folders, like `nesh`, `snesh`, `genh`, etc?  I asked in the [RetroPie forum](https://retropie.org.uk/forum/post/172739), but you might have missed it.  I read some where you were going on vacation or going out of town or something.  No worries.
